[package]
name = "wikipedia-to-epub"
version = "0.1.5"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Command line tool to generate epub book from Wikipedia pages"
keywords = ["cli", "kindle", "wikipedia", "epub"]
categories = ["command-line-utilities"]
readme = "README.md"
repository = "https://github.com/szabgab/wikipedia-to-epub.rs/"
homepage = "https://wikipedia-to-epub.code-maven.com/"
exclude = ["/examples/", "/expected/", "/pages/", "/site/", "/templates/", "/tests/", "/tools/"]


[dependencies]
any_ascii = "0.3.3"
clap = { version = "4.5.53", features = ["derive"] }
html-escape = "0.2.13"
regex = "1.12.2"
reqwest = { version = "0.13.4", default-features = false, features = ["blocking", "json", "rustls", "query"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_yaml = "0.9.34"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
uuid = { version = "1.23.2", features = ["v4"] }
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }
pulldown-cmark = { version = "0.13.4", default-features = false, features = ["html"] }
cached = "2.0.2"
xmlem = "0.4.1"

[dev-dependencies]
similar = "3.1.1"

[lints.clippy]
cargo        = { priority = -1, level = "deny" }
complexity   = { priority = -1, level = "deny" }
correctness  = { priority = -1, level = "deny" }


multiple_crate_versions = "allow" # I am not sure if we can fix this given that they are all brought in by dependencies
